name: dev_icons
description: A new Flutter package.
version: 1.0.0
homepage: https://github.com/JideGuru/dev_icons

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: DevIcons
      fonts:
        - asset: fonts/devicon.ttf